### ISSUE TITLE
The bandwidth is used much more times than actual download file

### ISSUE THREAD

**Issue by xin344** [RoyShen12/pornhub-downloader#2]
Hi, I use this downloader via a http proxy, and I found it will use approximately 5 times bandwidth than the file actual download size, and I can not point the issue, do anyone have ideas?

**Comment by RoyShen12** [comment]
I changed the request module to make-fetch-happen, the network traffic amount via proxy should reduce. Get the latest version and try again. Also notice that hundreds KB traffic will cost while crawling the search result pages and video detail pages per video.

**Comment by xin344** [comment]
Thanks for reply, I noticed that my proxy provider may enabled "BBR" feature, this can also cause this problem when packet loss, but not much as 5 times.

Thank you again for working on this!

**Comment by xin344** [comment]
刚刚看了readme.md发现好像你可以阅读中文？

**Comment by RoyShen12** [comment]
我是中国人emmm

**Comment by xin344** [comment]
哈哈哈 看出来了 为了隐蔽性 可能还是说英文比较好

**Comment by xin344** [comment]
I deleted the comments in order to ... as what you know. And I suggest you to delete the reply upside.
