### ISSUE TITLE
-l or --limit flag not working

### ISSUE THREAD

**Issue by xin344** [RoyShen12/pornhub-downloader#4]
Like it is in title, the flag not working and seems to be ignored by the script, I checked -l 500 and --limit 500, they were not working at all, if possible, pls check, thank you.

**Comment by RoyShen12** [comment]
You should notice that --limit 500 means 500MB limitation.
And this flag should work properly, since I just tested it.

**Comment by xin344** [comment]
I am sure about this, I have tried many times for this, downloading a video with -l 500 it will not stop at 500MB downloaded, it will download the entire video. 0.0

**Comment by RoyShen12** [comment]
The smallest unit of auto quit is video.
when every download finished, process will check the total download size, if its larger than the limitation, process will quit.
And in -k mode this limitation won't work.

**Comment by xin344** [comment]
Ok, got it!
