### ISSUE TITLE
Download not working anymore

### ISSUE THREAD

**Issue by soimy** [RoyShen12/pornhub-downloader#8]
videoUrl now return bunch of m3u8 playlist : [videoUrl] -> [master.m3u8] -> [index-v1-a1.m3u8]
The latter one return the true playlist video segments.

Return file attached. Need tweak of the download strategy which beyond my ablities.

[index-v1-a1.m3u8.txt](https://github.com/RoyShen12/pornhub-downloader/files/5861671/index-v1-a1.m3u8.txt)
[master.m3u8.txt](https://github.com/RoyShen12/pornhub-downloader/files/5861672/master.m3u8.txt)

**Comment by RoyShen12** [comment]
This time I'm too busy to maintain this repo anymore, and you may try this instead https://github.com/iawia002/annie
